apiVersion: v1
kind: Pod
metadata:
  name: compliant-safe-pod
spec:
  containers:
  - name: safe-nginx
    image: nginxinc/nginx-unprivileged:stable-alpine
    securityContext:
      runAsNonRoot: true
      runAsUser: 10001
